"""add next_run_at to subscription_state

Revision ID: 142f81a9e4ff
Revises: a6cd57d36cb5
Create Date: 2026-01-05 21:57:08.153599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f81a9e4ff'
down_revision: Union[str, Sequence[str], None] = 'a6cd57d36cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_state', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_state', 'next_run_at')
    # ### end Alembic commands ###