"""add register check

Revision ID: 1fd0b176809b
Revises: da0f70152520
Create Date: 2026-06-12 20:18:40.950912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd0b176809b'
down_revision: Union[str, Sequence[str], None] = 'da0f70152520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('lockout_level', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_level')
    op.drop_column('users', 'last_failed_login_at')
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###