"""bot link codes

Revision ID: 22d4a550d547
Revises: a461e19eaded
Create Date: 2026-03-04 19:22:49.573935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d4a550d547'
down_revision: Union[str, Sequence[str], None] = 'a461e19eaded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_link_codes_code_hash'), 'bot_link_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_bot_link_codes_user_id'), 'bot_link_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_link_codes_user_id'), table_name='bot_link_codes')
    op.drop_index(op.f('ix_bot_link_codes_code_hash'), table_name='bot_link_codes')
    op.drop_table('bot_link_codes')
    # ### end Alembic commands ###