"""add checkbox columns

Revision ID: 3d77d7336b35
Revises: 8be80746ee37
Create Date: 2026-04-29 20:49:26.988460

Добавляет в таблицу users поля для фиксации акцепта юр. документов
(Privacy Policy + Terms of Service + подтверждение возраста 16+) при
регистрации:

* terms_accepted_at — UTC-метка, когда пользователь принял документы;
* terms_accepted_version — строковая версия принятого комплекта документов
  (например, "1.0").

Поля nullable, чтобы существующие записи (созданные до внедрения чекбокса)
не ломались. Для новых регистраций оба поля заполняются эндпоинтом
/auth/register на основании payload-а из формы.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d77d7336b35'
down_revision: Union[str, Sequence[str], None] = '8be80746ee37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_version')
    op.drop_column('users', 'terms_accepted_at')
    # ### end Alembic commands ###