"""add history table

Revision ID: 5c2e7106924d
Revises: a553ec6e191b
Create Date: 2026-03-31 09:28:08.454389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2e7106924d'
down_revision: Union[str, Sequence[str], None] = 'a553ec6e191b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('chat_ref', sa.Text(), nullable=False),
    sa.Column('chat_ref_normalized', sa.Text(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_username', sa.String(length=128), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'source_mode', 'chat_ref_normalized', name='uq_user_chat_history_owner_source_ref')
    )
    op.create_index(op.f('ix_user_chat_history_chat_username'), 'user_chat_history', ['chat_username'], unique=False)
    op.create_index(op.f('ix_user_chat_history_id'), 'user_chat_history', ['id'], unique=False)
    op.create_index('ix_user_chat_history_owner_source_last', 'user_chat_history', ['owner_user_id', 'source_mode', 'last_accessed_at'], unique=False)
    op.create_index(op.f('ix_user_chat_history_owner_user_id'), 'user_chat_history', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_chat_history_source_mode'), 'user_chat_history', ['source_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chat_history_source_mode'), table_name='user_chat_history')
    op.drop_index(op.f('ix_user_chat_history_owner_user_id'), table_name='user_chat_history')
    op.drop_index('ix_user_chat_history_owner_source_last', table_name='user_chat_history')
    op.drop_index(op.f('ix_user_chat_history_id'), table_name='user_chat_history')
    op.drop_index(op.f('ix_user_chat_history_chat_username'), table_name='user_chat_history')
    op.drop_table('user_chat_history')
    # ### end Alembic commands ###