"""add max_chats_per_group_request

Revision ID: 85e4579b0777
Revises: f1934ba53ee2
Create Date: 2026-06-02 20:08:02.009344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4579b0777'
down_revision: Union[str, Sequence[str], None] = 'f1934ba53ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('max_chats_per_group_request', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'max_chats_per_group_request')
    # ### end Alembic commands ###