"""add service telegram account tables

Revision ID: a553ec6e191b
Revises: 5c8273706650
Create Date: 2026-03-23 09:25:47.602912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a553ec6e191b'
down_revision: Union[str, Sequence[str], None] = '5c8273706650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_phone_numbers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_e164', sa.String(length=32), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('last_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_phone_numbers_country_code'), 'service_phone_numbers', ['country_code'], unique=False)
    op.create_index(op.f('ix_service_phone_numbers_id'), 'service_phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_service_phone_numbers_phone_e164'), 'service_phone_numbers', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_service_phone_numbers_provider_code'), 'service_phone_numbers', ['provider_code'], unique=False)
    op.create_index('ix_service_phone_numbers_provider_country', 'service_phone_numbers', ['provider_code', 'country_code'], unique=False)
    op.create_table('service_telegram_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_busy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('busy_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_fail_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requests_last_minute', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requests_last_hour', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requests_last_day', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['service_phone_numbers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_telegram_accounts_cooldown_until'), 'service_telegram_accounts', ['cooldown_until'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_id'), 'service_telegram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_is_busy'), 'service_telegram_accounts', ['is_busy'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_is_enabled'), 'service_telegram_accounts', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_phone_number_id'), 'service_telegram_accounts', ['phone_number_id'], unique=False)
    op.create_index('ix_service_telegram_accounts_select', 'service_telegram_accounts', ['status', 'is_enabled', 'is_busy', 'cooldown_until'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_status'), 'service_telegram_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_service_telegram_accounts_telegram_user_id'), 'service_telegram_accounts', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_service_telegram_accounts_telegram_username'), 'service_telegram_accounts', ['telegram_username'], unique=False)
    op.create_table('service_account_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('service_account_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_ref', sa.Text(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_telegram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_account_logs_account_event_at', 'service_account_logs', ['service_account_id', 'event_at'], unique=False)
    op.create_index('ix_service_account_logs_account_started_at', 'service_account_logs', ['service_account_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_service_account_logs_event_at'), 'service_account_logs', ['event_at'], unique=False)
    op.create_index(op.f('ix_service_account_logs_event_type'), 'service_account_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_service_account_logs_id'), 'service_account_logs', ['id'], unique=False)
    op.create_index(op.f('ix_service_account_logs_service_account_id'), 'service_account_logs', ['service_account_id'], unique=False)
    op.create_table('service_account_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('service_account_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_telegram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_account_status_history_account_created', 'service_account_status_history', ['service_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_service_account_status_history_id'), 'service_account_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_service_account_status_history_service_account_id'), 'service_account_status_history', ['service_account_id'], unique=False)
    op.create_table('service_telegram_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('service_account_id', sa.BigInteger(), nullable=False),
    sa.Column('session_ciphertext', sa.Text(), nullable=False),
    sa.Column('session_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_telegram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_telegram_sessions_account_active', 'service_telegram_sessions', ['service_account_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_service_telegram_sessions_id'), 'service_telegram_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_service_telegram_sessions_is_active'), 'service_telegram_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_telegram_sessions_service_account_id'), 'service_telegram_sessions', ['service_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_telegram_sessions_service_account_id'), table_name='service_telegram_sessions')
    op.drop_index(op.f('ix_service_telegram_sessions_is_active'), table_name='service_telegram_sessions')
    op.drop_index(op.f('ix_service_telegram_sessions_id'), table_name='service_telegram_sessions')
    op.drop_index('ix_service_telegram_sessions_account_active', table_name='service_telegram_sessions')
    op.drop_table('service_telegram_sessions')
    op.drop_index(op.f('ix_service_account_status_history_service_account_id'), table_name='service_account_status_history')
    op.drop_index(op.f('ix_service_account_status_history_id'), table_name='service_account_status_history')
    op.drop_index('ix_service_account_status_history_account_created', table_name='service_account_status_history')
    op.drop_table('service_account_status_history')
    op.drop_index(op.f('ix_service_account_logs_service_account_id'), table_name='service_account_logs')
    op.drop_index(op.f('ix_service_account_logs_id'), table_name='service_account_logs')
    op.drop_index(op.f('ix_service_account_logs_event_type'), table_name='service_account_logs')
    op.drop_index(op.f('ix_service_account_logs_event_at'), table_name='service_account_logs')
    op.drop_index('ix_service_account_logs_account_started_at', table_name='service_account_logs')
    op.drop_index('ix_service_account_logs_account_event_at', table_name='service_account_logs')
    op.drop_table('service_account_logs')
    op.drop_index(op.f('ix_service_telegram_accounts_telegram_username'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_telegram_user_id'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_status'), table_name='service_telegram_accounts')
    op.drop_index('ix_service_telegram_accounts_select', table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_phone_number_id'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_is_enabled'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_is_busy'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_id'), table_name='service_telegram_accounts')
    op.drop_index(op.f('ix_service_telegram_accounts_cooldown_until'), table_name='service_telegram_accounts')
    op.drop_table('service_telegram_accounts')
    op.drop_index('ix_service_phone_numbers_provider_country', table_name='service_phone_numbers')
    op.drop_index(op.f('ix_service_phone_numbers_provider_code'), table_name='service_phone_numbers')
    op.drop_index(op.f('ix_service_phone_numbers_phone_e164'), table_name='service_phone_numbers')
    op.drop_index(op.f('ix_service_phone_numbers_id'), table_name='service_phone_numbers')
    op.drop_index(op.f('ix_service_phone_numbers_country_code'), table_name='service_phone_numbers')
    op.drop_table('service_phone_numbers')
    # ### end Alembic commands ###