"""add subscription_type to subscriptions

Revision ID: a6cd57d36cb5
Revises: d1524d40c0d3
Create Date: 2026-01-02 17:13:11.339594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cd57d36cb5'
down_revision: Union[str, Sequence[str], None] = 'd1524d40c0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscription_type', sa.String(length=30), server_default='events', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'subscription_type')
    # ### end Alembic commands ###