"""add user timezone security ai model fields

Revision ID: bf160fe7459b
Revises: c67c17b9097e
Create Date: 2026-04-14 13:32:07.874791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf160fe7459b'
down_revision: Union[str, Sequence[str], None] = 'c67c17b9097e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'subscriptions',
        sa.Column(
            'ai_model',
            sa.String(length=64),
            server_default='openai:gpt-4.1-mini',
            nullable=False
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'timezone',
            sa.String(length=64),
            server_default='UTC',
            nullable=False
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'logout_revokes_telegram',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'default_ai_model',
            sa.String(length=64),
            server_default='openai:gpt-4.1-mini',
            nullable=False
        )
    )

    # 👇 ВАЖНО: убираем default после заполнения
    op.alter_column('subscriptions', 'ai_model', server_default=None)
    op.alter_column('users', 'timezone', server_default=None)
    op.alter_column('users', 'logout_revokes_telegram', server_default=None)
    op.alter_column('users', 'default_ai_model', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_ai_model')
    op.drop_column('users', 'logout_revokes_telegram')
    op.drop_column('users', 'timezone')
    op.drop_column('subscriptions', 'ai_model')
    # ### end Alembic commands ###