"""add llm price

Revision ID: c020a5f3c2f5
Revises: 3d77d7336b35
Create Date: 2026-05-13 07:13:59.888478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c020a5f3c2f5'
down_revision: Union[str, Sequence[str], None] = '3d77d7336b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_pricing',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=False),
    sa.Column('input_price_per_1m_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_price_per_1m_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_pricing_active', 'llm_pricing', ['is_active'], unique=False)
    op.create_index('ix_llm_pricing_ai_model_unique', 'llm_pricing', ['ai_model'], unique=True)
    op.create_index(op.f('ix_llm_pricing_updated_by_user_id'), 'llm_pricing', ['updated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_pricing_updated_by_user_id'), table_name='llm_pricing')
    op.drop_index('ix_llm_pricing_ai_model_unique', table_name='llm_pricing')
    op.drop_index('ix_llm_pricing_active', table_name='llm_pricing')
    op.drop_table('llm_pricing')
    # ### end Alembic commands ###