"""add plans and limits

Revision ID: c67c17b9097e
Revises: 27f999b61012
Create Date: 2026-04-08 18:56:06.723720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c67c17b9097e'
down_revision: Union[str, Sequence[str], None] = '27f999b61012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('daily_qa_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_qa_limit', sa.Integer(), nullable=False),
    sa.Column('qa_history_days', sa.Integer(), nullable=False),
    sa.Column('max_active_subscriptions', sa.Integer(), nullable=False),
    sa.Column('min_subscription_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('trial_subscription_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trial_subscription_duration_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('has_chat_history', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('provider_variant_id', sa.String(length=128), nullable=True),
    sa.Column('provider_product_id', sa.String(length=128), nullable=True),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_id'), 'billing_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_plan_code'), 'billing_subscriptions', ['plan_code'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_customer_id'), 'billing_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_subscription_id'), 'billing_subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_billing_subscriptions_status'), 'billing_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    op.create_index('ix_billing_subscriptions_user_status', 'billing_subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_code', sa.String(length=32), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_code', 'period_type', 'period_start', name='uq_usage_counter_user_metric_period')
    )
    op.create_index(op.f('ix_usage_counters_id'), 'usage_counters', ['id'], unique=False)
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    op.create_index('ix_usage_counters_user_metric_period', 'usage_counters', ['user_id', 'metric_code', 'period_type', 'period_start'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=True),
    sa.Column('chat_ref', sa.Text(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=False)
    op.create_index(op.f('ix_usage_events_status'), 'usage_events', ['status'], unique=False)
    op.create_index(op.f('ix_usage_events_subscription_id'), 'usage_events', ['subscription_id'], unique=False)
    op.create_index('ix_usage_events_user_created', 'usage_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_index('ix_usage_events_user_type_created', 'usage_events', ['user_id', 'event_type', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_subscription_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_subscription_id'], ['billing_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_billing_subscription_id'), 'payments', ['billing_subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_user_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('subscriptions', sa.Column('is_trial', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscriptions', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_subscriptions_is_trial'), 'subscriptions', ['is_trial'], unique=False)
    op.create_index('ix_subscriptions_owner_active', 'subscriptions', ['owner_user_id', 'is_active'], unique=False)
    op.create_index('ix_subscriptions_owner_trial', 'subscriptions', ['owner_user_id', 'is_trial'], unique=False)

    op.bulk_insert(
        sa.table(
            'plans',
            sa.column('code', sa.String),
            sa.column('price_usd', sa.Numeric),
            sa.column('is_active', sa.Boolean),
            sa.column('daily_qa_limit', sa.Integer),
            sa.column('monthly_qa_limit', sa.Integer),
            sa.column('qa_history_days', sa.Integer),
            sa.column('max_active_subscriptions', sa.Integer),
            sa.column('min_subscription_interval_minutes', sa.Integer),
            sa.column('trial_subscription_limit', sa.Integer),
            sa.column('trial_subscription_duration_days', sa.Integer),
            sa.column('has_chat_history', sa.Boolean),
        ),
        [
            {
                'code': 'free',
                'price_usd': 0,
                'is_active': True,
                'daily_qa_limit': 3,
                'monthly_qa_limit': 60,
                'qa_history_days': 7,
                'max_active_subscriptions': 2,
                'min_subscription_interval_minutes': 180,
                'trial_subscription_limit': 2,
                'trial_subscription_duration_days': 5,
                'has_chat_history': False,
            },
            {
                'code': 'basic',
                'price_usd': 9,
                'is_active': True,
                'daily_qa_limit': 20,
                'monthly_qa_limit': 300,
                'qa_history_days': 30,
                'max_active_subscriptions': 5,
                'min_subscription_interval_minutes': 60,
                'trial_subscription_limit': 0,
                'trial_subscription_duration_days': 0,
                'has_chat_history': True,
            },
            {
                'code': 'pro',
                'price_usd': 24,
                'is_active': True,
                'daily_qa_limit': 60,
                'monthly_qa_limit': 1500,
                'qa_history_days': 90,
                'max_active_subscriptions': 20,
                'min_subscription_interval_minutes': 30,
                'trial_subscription_limit': 0,
                'trial_subscription_duration_days': 0,
                'has_chat_history': True,
            },
        ]
    )

    op.create_index(op.f('ix_users_plan'), 'users', ['plan'], unique=False)
    op.create_foreign_key(
        'fk_users_plan_plans',
        'users',
        'plans',
        ['plan'],
        ['code'],
        ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_plan_plans', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_plan'), table_name='users')
    op.drop_index('ix_subscriptions_owner_trial', table_name='subscriptions')
    op.drop_index('ix_subscriptions_owner_active', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_trial'), table_name='subscriptions')
    op.drop_column('subscriptions', 'trial_ends_at')
    op.drop_column('subscriptions', 'trial_started_at')
    op.drop_column('subscriptions', 'is_trial')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index('ix_payments_user_created', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_usage_events_user_type_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_user_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_subscription_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_status'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_usage_counters_user_metric_period', table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index('ix_billing_subscriptions_user_status', table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_status'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_subscription_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_customer_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_plan_code'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###