"""add digest_events

Revision ID: d1524d40c0d3
Revises: 40a1139db939
Create Date: 2026-01-02 16:09:52.959653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1524d40c0d3'
down_revision: Union[str, Sequence[str], None] = '40a1139db939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_message_id', sa.BigInteger(), nullable=True),
    sa.Column('end_message_id', sa.BigInteger(), nullable=True),
    sa.Column('messages_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('digest_text', sa.Text(), server_default='', nullable=False),
    sa.Column('llm_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notify_status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'end_message_id', name='uq_digest_subscription_endmsg')
    )
    op.create_index('ix_digest_subscription_created', 'digest_events', ['subscription_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_digest_subscription_created', table_name='digest_events')
    op.drop_table('digest_events')
    # ### end Alembic commands ###