"""add save zapros, new settings

Revision ID: da0f70152520
Revises: f3cc3b405d95
Create Date: 2026-06-11 12:10:29.953925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0f70152520'
down_revision: Union[str, Sequence[str], None] = 'f3cc3b405d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_queries_user_name')
    )
    op.create_index(op.f('ix_saved_queries_id'), 'saved_queries', ['id'], unique=False)
    op.create_index(op.f('ix_saved_queries_user_id'), 'saved_queries', ['user_id'], unique=False)
    op.create_index('ix_saved_queries_user_last_used', 'saved_queries', ['user_id', 'last_used_at'], unique=False)
    op.create_table('query_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('usage_event_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_history_conversation_created', 'query_history', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_history_conversation_id'), 'query_history', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_query_history_id'), 'query_history', ['id'], unique=False)
    op.create_index(op.f('ix_query_history_source_mode'), 'query_history', ['source_mode'], unique=False)
    op.create_index('ix_query_history_user_created', 'query_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.create_foreign_key('bot_link_codes_user_id_fkey', 'bot_link_codes', 'users', ['user_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key('bot_user_link_owner_user_id_fkey', 'bot_user_link', 'users', ['owner_user_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key('subscriptions_owner_user_id_fkey', 'subscriptions', 'users', ['owner_user_id'], ['id'],
                          ondelete='CASCADE')
    op.add_column('user_token_balances', sa.Column('low_balance_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('save_query_history', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'save_query_history')
    op.drop_column('user_token_balances', 'low_balance_notified_at')
    op.drop_constraint('subscriptions_owner_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('bot_user_link_owner_user_id_fkey', 'bot_user_link', type_='foreignkey')
    op.drop_constraint('bot_link_codes_user_id_fkey', 'bot_link_codes', type_='foreignkey')
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index('ix_query_history_user_created', table_name='query_history')
    op.drop_index(op.f('ix_query_history_source_mode'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_conversation_id'), table_name='query_history')
    op.drop_index('ix_query_history_conversation_created', table_name='query_history')
    op.drop_table('query_history')
    op.drop_index('ix_saved_queries_user_last_used', table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_user_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
