"""add llm price

Revision ID: f1934ba53ee2
Revises: c020a5f3c2f5
Create Date: 2026-06-01 20:12:50.789084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1934ba53ee2'
down_revision: Union[str, Sequence[str], None] = 'c020a5f3c2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token_balances',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('monthly_granted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('topup_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('token_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('related_event_id', sa.BigInteger(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_event_id'], ['usage_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_transactions_id'), 'token_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_token_transactions_reason'), 'token_transactions', ['reason'], unique=False)
    op.create_index('ix_token_tx_user_created', 'token_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('user_query_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_event_id', sa.BigInteger(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('detected_category', sa.String(length=32), nullable=True),
    sa.Column('detected_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('final_category', sa.String(length=32), nullable=True),
    sa.Column('selected_tier', sa.String(length=16), nullable=False),
    sa.Column('selected_model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_log_final_category', 'user_query_log', ['final_category'], unique=False)
    op.create_index('ix_query_log_user_created', 'user_query_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_query_log_id'), 'user_query_log', ['id'], unique=False)
    op.add_column('plans', sa.Column('monthly_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('plans', sa.Column('allowed_tiers', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("ARRAY['light']::varchar[]"), nullable=False))
    op.add_column('plans', sa.Column('topup_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'topup_enabled')
    op.drop_column('plans', 'allowed_tiers')
    op.drop_column('plans', 'monthly_tokens')
    op.drop_index(op.f('ix_user_query_log_id'), table_name='user_query_log')
    op.drop_index('ix_query_log_user_created', table_name='user_query_log')
    op.drop_index('ix_query_log_final_category', table_name='user_query_log')
    op.drop_table('user_query_log')
    op.drop_index('ix_token_tx_user_created', table_name='token_transactions')
    op.drop_index(op.f('ix_token_transactions_reason'), table_name='token_transactions')
    op.drop_index(op.f('ix_token_transactions_id'), table_name='token_transactions')
    op.drop_table('token_transactions')
    op.drop_table('user_token_balances')
    # ### end Alembic commands ###