"""add_group_subscriptions

Revision ID: f3cc3b405d95
Revises: 01d843970d11
Create Date: 2026-06-07 07:21:37.608155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cc3b405d95'
down_revision: Union[str, Sequence[str], None] = '01d843970d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_chat_state',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('chat_key', sa.Text(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'chat_key')
    )
    op.create_table('subscription_chats',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('chat_ref', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_username', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'position')
    )
    op.create_index('ix_subscription_chats_subscription', 'subscription_chats', ['subscription_id'], unique=False)
    op.add_column('digest_events', sa.Column('chat_ref', sa.Text(), nullable=True))
    op.add_column('digest_events', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('digest_events', sa.Column('chat_title', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_digest_subscription_endmsg'), 'digest_events', type_='unique')
    op.create_index('uq_digest_sub_chat_endmsg', 'digest_events', ['subscription_id', sa.literal_column('coalesce(chat_id, 0)'), 'end_message_id'], unique=True)
    op.add_column('match_events', sa.Column('chat_ref', sa.Text(), nullable=True))
    op.add_column('match_events', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('match_events', sa.Column('chat_title', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_match_subscription_message'), 'match_events', type_='unique')
    op.create_index('uq_match_sub_chat_msg', 'match_events', ['subscription_id', sa.literal_column('coalesce(chat_id, 0)'), 'message_id'], unique=True)
    op.add_column('subscriptions', sa.Column('is_group', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_subscriptions_is_group'), 'subscriptions', ['is_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_is_group'), table_name='subscriptions')
    op.drop_column('subscriptions', 'is_group')
    op.drop_index('uq_match_sub_chat_msg', table_name='match_events')
    op.create_unique_constraint(op.f('uq_match_subscription_message'), 'match_events', ['subscription_id', 'message_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('match_events', 'chat_title')
    op.drop_column('match_events', 'chat_id')
    op.drop_column('match_events', 'chat_ref')
    op.drop_index('uq_digest_sub_chat_endmsg', table_name='digest_events')
    op.create_unique_constraint(op.f('uq_digest_subscription_endmsg'), 'digest_events', ['subscription_id', 'end_message_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('digest_events', 'chat_title')
    op.drop_column('digest_events', 'chat_id')
    op.drop_column('digest_events', 'chat_ref')
    op.drop_index('ix_subscription_chats_subscription', table_name='subscription_chats')
    op.drop_table('subscription_chats')
    op.drop_table('subscription_chat_state')
    # ### end Alembic commands ###